# Generated by Django 5.2 on 2025-10-28 10:08

import django.db.models.deletion
import students.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Surname')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=20, verbose_name='Surname')),
                ('birthday', models.DateField(validators=[students.validators.real_age], verbose_name='Date of birth')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Photo')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'constraints': [models.UniqueConstraint(fields=('first_name', 'last_name', 'birthday'), name='Unique person constraint')],
            },
        ),
    ]
