# Generated by Django 5.2 on 2025-10-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='students/photos/', verbose_name='photo'),
        ),
    ]
